spring:
  application:
    name: content-center


  main:
    #当遇到同样名字的时候，是否允许覆盖注册
    allow-bean-definition-overriding: true


  # 数据库配置
  datasource:
    url: jdbc:mysql://192.168.247.128:3306/content_center?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    hikari:
      username: root
      password: 123
      # >= 6.x com.mysql.cj.jdbc.Driver
      # <= 5.x com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
        discovery:
          server-addr: 192.168.247.128:8848
          cluster-name: HZ
    #sentinel 配置
    sentinel:
      #打开/关闭sentinel对spring mvc端点的保护
      filter:
        enabled: true
#      transport:
#        dashboard: 192.168.247.128:8080

    #SpringCloudStream的配置
#    stream:
#      rocketmq:
#        binder:
#          name-server: 192.168.247.128:9876
#      binders:
#        output:
#          #用来指定topic
#          destination: stream-test-topic



server:
  port: 8082

#ribbon的配置 表示请求user-center服务的时候所使用的负载规则
user-center:
  ribbon:
    NFLoadBalancerRuleClassName: com.ylc.contentcenter.config.NacosSameClusterWeightRule
#修改ribbon中的懒加载或者启动全部加载的选项配置
ribbon:
  eager-load:
    enabled: true
    clients: user-center
#springboot中的日志打印
logging:
  level:
    com.ylc.contentcenter.feignclient.UserCenterFeignClient: debug
    com.alibaba.nacos: error

#feign细粒度的日志打印配置
feign:
  client:
    config:
    #想要调用的微服务的名称 如果想要全局配置 则将user-center 改成default
      user-center:
      #共有四种级别 none(默认)，basic, headers, full
        loggerLevel: basic
  #feign整合sentinel
  sentinel:
    enabled: true

  httpclient:
    #让feign使用apache httpclient做请求，而不是默认的urlconnection
    enabled: true
    #feign的最大连接数
    max-connections: 200
    #feign单个路径的最大连接数
    max-connections-per-route: 50

management:
  endpoints:
    web:
      exposure:
        include: '*'
#是否打开restTemplate整合得开关，一般在本地开发阶段关闭
resttemplate:
  sentinel:
    enabled: false

#与阿里的ahas整合
ahas.namespace: default
project.name: content-center
ahas.license: fff20f761893450daf49c02820588991

rocketmq:
  name-server: 192.168.247.128:9876
  producer:
    #这里如果不写group 程序启动会报错
    group: test_group
